server:
  port: 81

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200381
    url: jdbc:mysql://localhost:3306/neotest?serverTimezone=GMT%2B8
  neo4j:
    uri: bolt://192.168.91.132:7687
    authentication:
      username: neo4j
      password: 200381